name: yuandong
server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    date-format: yyyy-MM-dd HH:mm:ss
    parser:
      allow-missing-values: true
  jersey:
    application-path: /
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://139.9.113.221:5432/test?stringtype=unspecified
    #url: jdbc:postgresql://192.168.51.5:5432/test?stringtype=unspecified
    url: jdbc:postgresql://192.168.51.5:5432/yuandong?stringtype=unspecified
    username: pvuser
    password: Pvsu1125
    hikari:
      minimum-idle: 2
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 600000
      connection-timeout: 30000
mybatis-plus:
  type-aliases-package: com.pvsoul.eec.yuandong.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{x-request-id}] %-5level %logger{50} - %msg%n'
  level:
    root: info
    #com.chz.mapper: debug

